import type { Recipe } from "./types"

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Creamy Garlic Parmesan Pasta",
    description: "A rich and creamy pasta dish with garlic and parmesan cheese that's ready in just 20 minutes.",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    tags: ["Pasta", "Italian", "Quick"],
    ingredients: [
      "8 oz fettuccine pasta",
      "2 tbsp butter",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Cook pasta according to package instructions. Reserve 1/2 cup of pasta water before draining.",
      "In a large skillet, melt butter over medium heat. Add minced garlic and sauté for 1-2 minutes until fragrant.",
      "Pour in heavy cream and bring to a simmer. Cook for 2-3 minutes until slightly thickened.",
      "Reduce heat to low and gradually whisk in parmesan cheese until melted and smooth.",
      "Add drained pasta to the sauce and toss to coat. If needed, add reserved pasta water to thin the sauce.",
      "Season with salt and pepper to taste. Garnish with fresh parsley before serving.",
    ],
  },
  {
    id: "2",
    title: "Avocado Toast with Poached Egg",
    description: "A nutritious breakfast featuring creamy avocado and perfectly poached eggs on toasted bread.",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    difficulty: "Medium",
    tags: ["Breakfast", "Healthy", "Vegetarian"],
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "2 eggs",
      "1 tbsp white vinegar",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
      "Fresh herbs for garnish",
    ],
    instructions: [
      "Toast the bread slices until golden brown.",
      "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl. Mash with a fork and season with salt and pepper.",
      "For the poached eggs, bring a pot of water to a gentle simmer and add vinegar.",
      "Crack each egg into a small bowl. Create a gentle whirlpool in the water and carefully slide the eggs in.",
      "Cook for 3-4 minutes for a runny yolk. Remove with a slotted spoon and place on paper towels to drain.",
      "Spread the mashed avocado on the toast slices and top each with a poached egg.",
      "Season with salt, pepper, and red pepper flakes if desired. Garnish with fresh herbs.",
    ],
  },
  {
    id: "3",
    title: "Honey Soy Glazed Salmon",
    description: "Tender salmon fillets glazed with a sweet and savory honey soy sauce, perfect for a quick dinner.",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    tags: ["Seafood", "Asian", "Healthy"],
    ingredients: [
      "4 salmon fillets (6 oz each)",
      "3 tbsp honey",
      "3 tbsp soy sauce",
      "2 tbsp olive oil",
      "2 cloves garlic, minced",
      "1 tbsp fresh ginger, grated",
      "1 tbsp rice vinegar",
      "Sesame seeds and green onions for garnish",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper.",
      "In a bowl, whisk together honey, soy sauce, olive oil, garlic, ginger, and rice vinegar.",
      "Place salmon fillets on the prepared baking sheet and brush with half of the glaze.",
      "Bake for 5 minutes, then brush with remaining glaze and bake for another 7-10 minutes until salmon is cooked through.",
      "Garnish with sesame seeds and sliced green onions before serving.",
    ],
  },
  {
    id: "4",
    title: "Classic Margherita Pizza",
    description: "A simple yet delicious pizza with fresh tomatoes, mozzarella, and basil on a crispy homemade crust.",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    tags: ["Pizza", "Italian", "Vegetarian"],
    ingredients: [
      "1 lb pizza dough",
      "1/2 cup tomato sauce",
      "8 oz fresh mozzarella, sliced",
      "2 tomatoes, sliced",
      "Fresh basil leaves",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 475°F (245°C) with a pizza stone if available.",
      "Roll out the pizza dough on a floured surface to your desired thickness.",
      "Transfer the dough to a pizza peel or baking sheet lined with parchment paper.",
      "Spread tomato sauce evenly over the dough, leaving a small border for the crust.",
      "Arrange mozzarella and tomato slices on top. Drizzle with olive oil and season with salt and pepper.",
      "Bake for 12-15 minutes until the crust is golden and the cheese is bubbly.",
      "Remove from oven and top with fresh basil leaves before serving.",
    ],
  },
  {
    id: "5",
    title: "Chocolate Chip Cookies",
    description:
      "Classic homemade chocolate chip cookies with a soft center and crispy edges, perfect for any occasion.",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: "Easy",
    tags: ["Dessert", "Baking", "Cookies"],
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp salt",
      "1 cup unsalted butter, softened",
      "3/4 cup granulated sugar",
      "3/4 cup packed brown sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "2 cups chocolate chips",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.",
      "In a small bowl, whisk together flour, baking soda, and salt.",
      "In a large bowl, beat butter, granulated sugar, and brown sugar until creamy.",
      "Add eggs one at a time, beating well after each addition. Stir in vanilla.",
      "Gradually beat in flour mixture. Stir in chocolate chips.",
      "Drop rounded tablespoons of dough onto prepared baking sheets.",
      "Bake for 9-12 minutes until edges are golden but centers are still soft.",
      "Cool on baking sheets for 2 minutes, then transfer to wire racks to cool completely.",
    ],
  },
  {
    id: "6",
    title: "Vegetable Stir Fry",
    description: "A colorful and nutritious stir fry loaded with fresh vegetables and a flavorful sauce.",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    tags: ["Vegetarian", "Asian", "Quick"],
    ingredients: [
      "2 tbsp vegetable oil",
      "2 cloves garlic, minced",
      "1 tbsp fresh ginger, grated",
      "1 bell pepper, sliced",
      "1 carrot, julienned",
      "1 cup broccoli florets",
      "1 cup snap peas",
      "1 cup mushrooms, sliced",
      "3 tbsp soy sauce",
      "1 tbsp honey",
      "1 tsp sesame oil",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Heat vegetable oil in a large wok or skillet over high heat.",
      "Add garlic and ginger, stir fry for 30 seconds until fragrant.",
      "Add vegetables, starting with the ones that take longer to cook (carrots, broccoli), then add quicker-cooking vegetables (bell pepper, snap peas, mushrooms).",
      "Stir fry for 5-7 minutes until vegetables are crisp-tender.",
      "In a small bowl, whisk together soy sauce, honey, and sesame oil.",
      "Pour sauce over vegetables and toss to coat. Cook for another 1-2 minutes.",
      "Garnish with sesame seeds before serving. Serve over rice or noodles if desired.",
    ],
  },
]

// Add user data for authentication
export const users = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john@example.com",
    password: "password123", // In a real app, this would be hashed
    favorites: ["1", "3"],
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane@example.com",
    password: "password456", // In a real app, this would be hashed
    favorites: ["2", "5"],
  },
]
