name : Deploy Docker Image to EC2.

on: 
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./Backend

jobs:

  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          platforms: linux/amd64
          push: true
          tags: cluelesslycoding/pantrypal-aws:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  deploy: 
    needs: build 
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Pull Docker Image
        run: sudo docker pull cluelesslycoding/pantrypal-aws:latest
      - name: Delete Prior Docker Containers
        run: sudo docker container prune 
      - name: Delete Prior Docker Images
        run: sudo docker image prune  
      - name: Run Docker Instance/Container 
        run: sudo docker run -d -p 80:8080 --env-file .env cluelesslycoding/pantrypal-aws:latest